package de.andreasbubolz.annotator.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LayoutAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLayoutAllPropertiesEquals(Layout expected, Layout actual) {
        assertLayoutAutoGeneratedPropertiesEquals(expected, actual);
        assertLayoutAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLayoutAllUpdatablePropertiesEquals(Layout expected, Layout actual) {
        assertLayoutUpdatableFieldsEquals(expected, actual);
        assertLayoutUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLayoutAutoGeneratedPropertiesEquals(Layout expected, Layout actual) {
        assertThat(expected)
            .as("Verify Layout auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLayoutUpdatableFieldsEquals(Layout expected, Layout actual) {
        assertThat(expected)
            .as("Verify Layout relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getCreated_at()).as("check created_at").isEqualTo(actual.getCreated_at()))
            .satisfies(e -> assertThat(e.getUpdated_at()).as("check updated_at").isEqualTo(actual.getUpdated_at()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLayoutUpdatableRelationshipsEquals(Layout expected, Layout actual) {}
}
