package de.andreasbubolz.annotator.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TextAnnotationElementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTextAnnotationElementAllPropertiesEquals(TextAnnotationElement expected, TextAnnotationElement actual) {
        assertTextAnnotationElementAutoGeneratedPropertiesEquals(expected, actual);
        assertTextAnnotationElementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTextAnnotationElementAllUpdatablePropertiesEquals(
        TextAnnotationElement expected,
        TextAnnotationElement actual
    ) {
        assertTextAnnotationElementUpdatableFieldsEquals(expected, actual);
        assertTextAnnotationElementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTextAnnotationElementAutoGeneratedPropertiesEquals(
        TextAnnotationElement expected,
        TextAnnotationElement actual
    ) {
        assertThat(expected)
            .as("Verify TextAnnotationElement auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTextAnnotationElementUpdatableFieldsEquals(TextAnnotationElement expected, TextAnnotationElement actual) {
        assertThat(expected)
            .as("Verify TextAnnotationElement relevant properties")
            .satisfies(e -> assertThat(e.getStartSec()).as("check startSec").isEqualTo(actual.getStartSec()))
            .satisfies(e -> assertThat(e.getText()).as("check text").isEqualTo(actual.getText()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTextAnnotationElementUpdatableRelationshipsEquals(
        TextAnnotationElement expected,
        TextAnnotationElement actual
    ) {
        assertThat(expected)
            .as("Verify TextAnnotationElement relationships")
            .satisfies(e -> assertThat(e.getAnnotation()).as("check annotation").isEqualTo(actual.getAnnotation()));
    }
}
