version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: annotator
      POSTGRES_PASSWORD: jhfvb7834kd4356%&
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - mynetwork

  jhipster-app:
    image: openjdk:17-jdk-slim
    container_name: jhipster-app
    volumes:
      - ./app.jar:/app.jar
    environment:
      - JAVA_OPTS=-Xmx512m
      - YOUTUBE_API_KEY=$YOUTUBE_API_KEY
      - SPRING_DATASOURCE_PASSWORD=jhfvb7834kd4356%& #${POSTGRES_PASSWORD}
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    command: 'java -jar app.jar --spring.profiles.active=prod'
    restart: always
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
